### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by larshp** [LinkeIT/AWS_S3_SDK_for_ABAP_Z#1]
Hi Jordi,
I installed the code using abapGit in one of my test systems, installed without any issues 😄 

Can you add a LICENSE file in this repository? See:

https://help.github.com/articles/adding-a-license-to-a-repository/

**Comment by JordiEscoda** [comment]
Hi Lars, 
Many thanks.
I added LICENSE file, GNU
I was able to upload go Github using abapGit without any issues. abapGit is great!
Please read and follow installation instructions if you want to try S3 for ABAP. 
You will find the program ZLNKERS3_STRUST to automatically install AWS SSL certificates to STRUST. You may use the same program with little modifications to install SSL certificate automatically for abapGit!
